core/urls.py
# pylint: disable=missing-module-docstring

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Configuracion de la ruta de autenticacion con las vistas que trae django incluidas:
    path('', include('home.urls')),
    
    path('inventario/', include('inventario.urls')),
    
    path('compras/', include('compras.urls')),
    
    path('login/', auth_views.LoginView.as_view(template_name="base/login.html"), name="login"),
    
    path('logout/', auth_views.LogoutView.as_view(template_name="base/login.html"), name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario/urls.py
from django.urls import path
from inventario.views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDelete, SubCategoriaView, SubCategoriaAdd, SubCategoriaEdit, SubCategoriaDelete, MarcaView, MarcaAdd, MarcaEdit, marca_disable, marca_enable, UniMedidasView, UniMedidasAdd, UniMedidasEdit,unimedida_disable, unimedida_enable, ProductoView, ProductoAdd, ProductoEdit, producto_enable, producto_disable

app_name = "inventario"

urlpatterns = [
    path("categorias/", CategoriaView.as_view(), name="categorias"),
    path("categorias/new", CategoriaNew.as_view(),name="categoria-new"),
    path("categoria/edit/<int:pk>", CategoriaEdit.as_view(), name="categoria-edit"),
    path("categoria/delete/<int:pk>", CategoriaDelete.as_view(), name="categoria-delete"),
    
    path("subcategorias/", SubCategoriaView.as_view(), name="subcategorias"),
    path("subcategorias/new",SubCategoriaAdd.as_view(), name="subcategoria-new"),
    path("subcategorias/edit/<int:pk>", SubCategoriaEdit.as_view(), name="subcategoria-edit"),
    path("subcategorias/delete/<int:pk>",SubCategoriaDelete.as_view(), name="subcategoria-delete"),
    
    path("marcas/", MarcaView.as_view(), name= "marcas"),
    path("marcas/new",MarcaAdd.as_view(),name="marca-new"),
    path("marcas/edit/<int:pk>", MarcaEdit.as_view(), name="marca-edit"),
    path("marcas/disable/<int:marca_id>", marca_disable , name="marca-disable"),
    path("marcas/enable/<int:marca_id>", marca_enable, name="marca-enable"),
    
    path("unimedidas/", UniMedidasView.as_view(), name="unimedidas"),
    path("unimedidas/new", UniMedidasAdd.as_view(), name="unimedida-new"),
    path("unimedidas/edit/<int:pk>", UniMedidasEdit.as_view(), name="unimedida-edit"),
    path("unimedidas/disable/<int:unimedida_id>",unimedida_disable, name="unimedida-disable"),
    path("unimedidas/enable/<int:unimedida_id>",unimedida_enable, name="unimedida-enable"),
    
    path("productos/", ProductoView.as_view(), name="productos"),
    path("productos/new",ProductoAdd.as_view(), name="producto-new" ),
    path("productos/edit/<int:pk>", ProductoEdit.as_view(), name="producto-edit"),
    path("productos/disable/<int:producto_id>", producto_disable, name="producto-disable"),
    path("productos/enable/<int:producto_id>", producto_enable, name="producto-enable"),
    
    
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Modelo(models.Model):
    
    estado = models.BooleanField(default=True)
    fcreacion = models.DateTimeField(auto_now_add=True)
    fmodificacion = models.DateTimeField(auto_now=True)
    ucreacion = models.ForeignKey(User, on_delete=models.CASCADE)
    umodificacion = models.IntegerField(null=True, blank=True)
    
    class Meta:
        abstract = True
    
    

inventario/models.py
from django.db import models
from home.models import Modelo

# Create your models here.

class Categoria (Modelo):
    
    descripcion = models.CharField(max_length=100, help_text="Descripcion de la nueva categoria", unique=True)
    
    def __str__(self):
        return f'{self.descripcion}'
    
    def save(self, **args):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save(**args)
    
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "categorias"
        
class SubCategoria(Modelo):
    
    categoriapadre = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, blank=True)
    
    descripcion = models.CharField(max_length=100, help_text="Descripcion de la nueva subcategoria")
    
    def __str__(self):
        if self.categoriapadre:
            return f"{self.categoriapadre.descripcion} > {self.descripcion}"    
        return f"Sin Categoria Padre > {self.descripcion}"
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()
        
    class Meta:
        verbose_name = "sub categoria"
        verbose_name_plural = "Sub categorias"
        unique_together = ('categoriapadre', 'descripcion')
        
class Marca(Modelo):
    
    descripcion = models.CharField(max_length=100, help_text="Nombre de la marca", unique=True)
    
    def __str__(self):
        return f'{self.descripcion}'
    
    def save(self, **args):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save(**args)
    
    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"
        
class UnidadesMedidas(Modelo):
    
    descripcion = models.CharField(max_length=100, help_text="Nombre de la unidad", unique=True)
    
    def __str__(self):
        return f'{self.descripcion}'
    
    def save(self, **args):
        self.descripcion = self.descripcion.upper()
        super(UnidadesMedidas, self).save(**args)
    
    class Meta:
        verbose_name = "Unidad de medida"
        verbose_name_plural = "Unidades de medidas"
        
class Producto(Modelo):
    
    codigo = models.CharField(max_length=20, unique=True)
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia_producto = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)
    
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadesMedidas, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.descripcion}"
    
    def save(self, **args):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save(**args)
    
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barra')

inventario/forms.py
from django import forms
from inventario.models import Categoria, SubCategoria, Marca, UnidadesMedidas, Producto

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion':"categoria", 'estado':"Estado"}
        widget = {'descripcion': forms.TextInput}
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})
            
class SubCategoriaForm(forms.ModelForm):
    class Meta:
        model = SubCategoria
        fields = ['categoriapadre','descripcion', 'estado']
        labels = {'descripcion':"Sub Categoria", 'estado':"Estado"}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})    

        self.fields['categoriapadre'].empty_label = "Seleccione Categoria"
        
class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion':"Marca", 'estado':"Estado"}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})
                
class UnidadesMedidasForm(forms.ModelForm):
    class Meta:
        model = UnidadesMedidas
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de medida', 'estado':'estado'}
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})
            
class ProductosForm(forms.ModelForm):
    class Meta:
        model = Producto
        field = ['codigo', 'codigo_barra', 'descripcion', 'estado', 'precio', 'existencia_producto', 'ultima_compra', 'marca', 'subcategoria', 'unidad_medida']
        
        exclude = ['umodificacion','fmodificacion','ucreacion','fcreacion']
        
        widget = {'descripcion': forms.TextInput()}
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia_producto'].widget.attrs['readonly'] = True
        

inventario/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from inventario.models import Categoria, SubCategoria, Marca, UnidadesMedidas, Producto
from inventario.forms import CategoriaForm, SubCategoriaForm, MarcaForm, UnidadesMedidasForm, ProductosForm

class CategoriaView(LoginRequiredMixin, ListView):
    
    model = Categoria
    template_name = "inventario/lista_categoria.html"
    context_object_name = "categorias"
    login_url = "/login/"
    
class CategoriaNew(LoginRequiredMixin,CreateView):
    
    model = Categoria
    template_name = "inventario/add_categoria.html"
    login_url = "/login/"
    form_class = CategoriaForm
    success_url = reverse_lazy("inventario:categorias") 

    def form_valid(self, form):
        form.instance.ucreacion = self.request.user
        return super().form_valid(form)
    

class CategoriaEdit(LoginRequiredMixin,UpdateView):
    
    model = Categoria
    template_name = "inventario/add_categoria.html"
    login_url = "/login/"
    context_object_name = "categoria"
    form_class = CategoriaForm
    success_url = reverse_lazy("inventario:categorias")
    
    def form_valid(self, form):
        form.instance.umodificacion = self.request.user.id
        return super().form_valid(form)

class CategoriaDelete(LoginRequiredMixin, DeleteView):
    
    model = Categoria
    template_name = "inventario/borrar_categorias.html"
    context_object_name = "categoria"
    login_url = "/login/"
    success_url = reverse_lazy("inventario:categorias")
    
class SubCategoriaView(LoginRequiredMixin,ListView):
    
    model = SubCategoria
    template_name = "inventario/lista_subcategoria.html"
    context_object_name = "subcategorias"
    login_url = "/login/"
    
class SubCategoriaAdd(LoginRequiredMixin,CreateView):
    
    model = SubCategoria
    template_name = "inventario/add_subcategoria.html"
    login_url = "/login/"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inventario:subcategorias")
    
    def form_valid(self, form):
        form.instance.ucreacion = self.request.user
        return super().form_valid(form)
    
        
class SubCategoriaEdit(LoginRequiredMixin, UpdateView):
    
    model = SubCategoria
    template_name = "inventario/add_subcategoria.html"
    login_url = "/login/"
    context_object_name = "subcategoria"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inventario:subcategorias")
    
    def form_valid(self, form):
        form.instance.umodificacion = self.request.user.id
        return super().form_valid(form)
    
class SubCategoriaDelete(LoginRequiredMixin, DeleteView):
    
    model = SubCategoria
    template_name = "inventario/borrar_subcategorias.html"
    login_url = "/login/"
    context_object_name = "subcategoria"
    success_url = reverse_lazy("inventario:subcategorias")

class MarcaView(LoginRequiredMixin, ListView):
    
    model = Marca
    template_name = "inventario/lista_marcas.html"
    context_object_name = "marcas"
    login_url = "/login/"
    
class MarcaAdd(LoginRequiredMixin, CreateView):
    
    model = Marca
    template_name = "inventario/add_marca.html"
    login_url = "/login/"
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:marcas")
    
    def form_valid(self, form):
        form.instance.ucreacion = self.request.user
        return super().form_valid(form)
    
class MarcaEdit(LoginRequiredMixin, UpdateView):
    model = Marca
    template_name = "inventario/add_marca.html"
    context_object_name = "marca"
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:marcas")
    
    def form_valid(self, form):
        form.instance.umodificacion = self.request.user.id
        return super().form_valid(form)

@login_required
def marca_disable(request,marca_id):

    marca = get_object_or_404(Marca, id = marca_id)
    
    ctx = {
        'marca':marca,
    }
    
    if request.method == "POST":
        marca.estado = False
        marca.save()
        return redirect("inventario:marcas")
    
    return render(request, "inventario/disable_marca.html", ctx)
    
@login_required
def marca_enable(request, marca_id):
    
    marca = get_object_or_404(Marca, id = marca_id)
    
    template_name = "inventario/enable_marca.html"
    ctx = {
        'marca':marca,
    }
    
    if request.method == "POST":
        marca.estado = True
        marca.save()
        return redirect("inventario:marcas")
    
    return render(request, template_name, ctx)

class UniMedidasView(LoginRequiredMixin, ListView):
     model = UnidadesMedidas
     login_url = "/login/"
     template_name = "inventario/lista_unidadesmedidas.html"
     context_object_name = "unimedidas"
     
class UniMedidasAdd(LoginRequiredMixin, CreateView):
    model = UnidadesMedidas
    login_url = "/login/"
    template_name = "inventario/add_unidadesmedidas.html"
    form_class = UnidadesMedidasForm
    success_url = reverse_lazy("inventario:unimedidas")
    
    def form_valid(self, form):
        form.instance.ucreacion = self.request.user
        return super().form_valid(form)
    
class UniMedidasEdit(LoginRequiredMixin, UpdateView):
    model = UnidadesMedidas
    login_url = "/login/"
    template_name = "inventario/add_unidadesmedidas.html"
    form_class = UnidadesMedidasForm
    success_url = reverse_lazy("inventario:unimedidas")
    context_object_name = "unimedida"
    
    def form_valid(self, form):
        form.instance.umodificacion = self.request.user.id
        return super().form_valid(form)

@login_required
def unimedida_disable(request, unimedida_id):
    
    unimedida = get_object_or_404(UnidadesMedidas, id = unimedida_id)
    
    ctx = {
        'unimedida' : unimedida,
    }
    
    if request.method == "POST":
        unimedida.estado = False
        unimedida.save()
        return redirect("inventario:unimedidas")
    
    return render(request, "inventario/disable_unimedida.html", ctx)


@login_required
def unimedida_enable(request, unimedida_id):
    
    unimedida = get_object_or_404(UnidadesMedidas, id = unimedida_id)
    
    ctx = {
        'unimedida':unimedida,
    }
    
    if request.method == "POST":
        unimedida.estado = True
        unimedida.save()
        return redirect("inventario:unimedidas")
    
    return render(request, "inventario/enable_unimedida.html", ctx)

class ProductoView(LoginRequiredMixin, ListView):
    
    model = Producto
    login_url = "/login/"
    template_name = "inventario/lista_productos.html"
    context_object_name = "productos"
    

class ProductoAdd(LoginRequiredMixin, CreateView):
    
    model = Producto
    login_url = "/login/"
    template_name = "inventario/add_producto.html"
    success_url = reverse_lazy("inventario:productos")
    form_class = ProductosForm
    
    def form_valid(self, form):
        form.instance.ucreacion = self.request.user
        return super().form_valid(form)
    
class ProductoEdit(LoginRequiredMixin, UpdateView):
    
    model = Producto
    login_url = "/login/"
    template_name = "inventario/add_producto.html"
    context_object_name = "producto"
    success_url = reverse_lazy("inventario:productos")
    form_class = ProductosForm
    
    def form_valid(self, form):
        form.instance.umodificacion = self.request.user.id
        return super().form_valid(form)
    
@login_required
def producto_disable(request, producto_id):
    
    producto = get_object_or_404(Producto, id=producto_id)
    
    ctx = {
        'producto':producto,
    }
    
    if request.method == "POST":
        producto.estado = False
        producto.save()
        return redirect("inventario:productos")

    return render(request, "inventario/disable_producto.html", ctx)

@login_required
def producto_enable(request, producto_id):
    
    producto = get_object_or_404(Producto, id = producto_id)
    
    ctx = {
        'producto':producto,
    }
    
    if request.method == "POST":
        producto.estado = True
        producto.save()
        return redirect("inventario:productos")
    
    return render(request, "inventario/enable_producto.html", ctx)
    

inventario/templates/inventario/borrar_subcategorias.html
{% extends "base/base.html" %} 
{% block pagecontent %}

<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-bottom-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">
              De verdad desea eliminar la Sub categoria?
              <span>{{subcategoria.descripcion}} </span>
            </div>

            <div class="dropdown-divider"></div>

            <button type="submit" class="btn btn-danger">Si, Eliminar</button>
            <div class="dropdown-divider"></div>
            <a href=" {% url 'inventario:subcategorias' %}" class="btn btn-success"
              ><i class="fas fa-undo"></i>Cancelar</a
            >
          </div>

          <div class="col-auto">
            <i class="fas fa-trash fa-2x text-gray-300" aria-hidden="true"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock pagecontent %}

{% block footer %}{% endblock footer %}

inventario/templates/inventario/lista_marcas.html
{% extends "base/base.html" %} 

{% block pagecontent %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h6 class="m-0 font-weight-bold text-primary">Lista de Marcas</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" href="{% url 'inventario:marca-new' %}">
          <i class="far fa-calendar-plus"></i> Nueva Marca</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Nueva funcion</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not marcas %}
    <div class="alert alert-info">No hay Marcas</div>
    {% else %}

    <table class="table table-striped-hover" id="MyTable">
      <thead>
        <th>ID</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>Fecha creacion</th>
        <th>Fecha modificacion</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for marca in marcas %}
        <tr>
          <td>{{marca.id}}</td>
          <td>{{marca.descripcion}}</td>
          <td>{{marca.estado |yesno:"Activo, Inactivo"}}</td>
          <td>{{marca.fcreacion | date:"d/m/Y H:i:s"}}</td>
          <td>{{marca.fmodificacion | date:"d/m/Y H:i:s"}}</td>

          <td>
            <a
              href="{% url 'inventario:marca-edit' marca.id %}"
              class="btn btn-warning btn-circle"
              role="button"
              ><i class="far fa-edit"></i
            ></a>

            {% if marca.estado %}
            
              <a href="{% url 'inventario:marca-disable' marca.id %}" class="btn btn-danger btn-circle" role="button">
                <i class="far fa-thumbs-down"></i
              ></a>
            {% else %}
              <a href="{% url 'inventario:marca-enable' marca.id %}" class="btn btn-success btn-circle" role="button">
              <i class="far fa-thumbs-up"></i
              ></a>
            {% endif %}
              

          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock pagecontent %}

{% block js %}

<script>
  $(document).ready(function(){
    $('#MyTable').DataTable();
  });
</script>

{% endblock js %}

inventario/templates/inventario/lista_productos.html
{% extends "base/base.html" %} 

{% block pagecontent %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" href="#" onClick="return abrir_modal('{% url 'inventario:producto-new' %}')">
          <i class="far fa-calendar-plus"></i> Nuevo Producto</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Nueva funcion</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not productos %}
    <div class="alert alert-info">No hay Productos</div>
    {% else %}

    <table class="table table-striped-hover" id="MyTable">
      <thead>
        <th>Sub. Categoria</th>
        <th>Codigo</th>
        <th>C. Barra</th>
        <th>Descripcion</th>
        <th>Existencia</th>
        <th>Marca</th>
        <th>U. de medida</th>
        <th>Estado</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for producto in productos %}
        <tr>
          <td>{{producto.subcategoria}}</td>
          <td>{{producto.codigo}}</td>
          <td>{{producto.codigo_barra}}</td>
          <td>{{producto.descripcion}}</td>
          <td>{{producto.existencia_producto}}</td>
          <td>{{producto.marca}}</td>
          <td>{{producto.unidad_medida}}</td>
          <td>{{producto.estado |yesno:"Activo, Inactivo"}}</td>
          <td>
            <a
              href="#"
              class="btn btn-warning btn-circle"
              role="button"

              onClick="return abrir_modal('{% url 'inventario:producto-edit' producto.id %}')"

              ><i class="far fa-edit"></i
            ></a>

            {% if producto.estado %}
            
              <a href="{% url 'inventario:producto-disable' producto.id %}" class="btn btn-danger btn-circle" role="button">
                <i class="far fa-thumbs-down"></i
              ></a>
            {% else %}
              <a href="{% url 'inventario:producto-enable' producto.id %}" class="btn btn-success btn-circle" role="button">
              <i class="far fa-thumbs-up"></i
              ></a>
            {% endif %}
              

          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock pagecontent %}

{% block js %}

<script>
  $(document).ready(function(){
    $('#MyTable').DataTable();
  });
</script>

{% endblock js %}

inventario/templates/inventario/lista_unidadesmedidas.html
{% extends "base/base.html" %} 
{% load static %}

{% block pagecontent %}

<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h6 class="m-0 font-weight-bold text-primary">Lista de Unidades de medida</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" href="{% url 'inventario:unimedida-new' %}"> <i class="far fa-calendar-plus"></i> Nueva Unidad de medida</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    
    {% if not unimedidas %} 
      <div class="alert alert-info">
        No hay Unidades de medida
      </div>
    {% else %}
 
    <table class="table table-striped-hover" id="MyTable" >
      <thead>
        <th>ID</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>Fecha creacion</th>
        <th>Fecha modificacion</th>
        <th class="all">Acciones</th>
      </thead>

      <tbody>
        {% for unimedida in unimedidas %}
        <tr>
            
          <td>{{unimedida.id}}</td>
          <td>{{unimedida.descripcion}}</td>
          <td>{{unimedida.estado |yesno:"Activo, Inactivo"}}</td>
          <td>{{unimedida.fcreacion | date:"d/m/Y H:i:s"}}</td>
          <td>{{unimedida.fmodificacion | date:"d/m/Y H:i:s"}}</td>

          <td>
            <a
              href="{% url 'inventario:unimedida-edit' unimedida.id %}"
              class="btn btn-warning btn-circle"
              role="button"
              ><i class="far fa-edit"></i
            ></a>

            {% if unimedida.estado %}
            
              <a href="{% url 'inventario:unimedida-disable' unimedida.id %}" class="btn btn-danger btn-circle" role="button">
                <i class="far fa-thumbs-down"></i
              ></a>
            {% else %}
              <a href="{% url 'inventario:unimedida-enable' unimedida.id %}" class="btn btn-success btn-circle" role="button">
              <i class="far fa-thumbs-up"></i
              ></a>
            {% endif %}
              

          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endblock pagecontent %} 

{% block js %}

<script>
  $(document).ready(function(){
    $('#MyTable').DataTable();
  });
</script>

{% endblock js %}