core/urls.py
# pylint: disable=missing-module-docstring

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Configuracion de la ruta de autenticacion con las vistas que trae django incluidas:
    path('', include('home.urls')),
    
    path('inventario/', include('inventario.urls')),
    
    path('compras/', include('compras.urls')),
    
    path('login/', auth_views.LoginView.as_view(template_name="base/login.html"), name="login"),
    
    path('logout/', auth_views.LogoutView.as_view(template_name="base/login.html"), name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
# pylint: disable=missing-module-docstring
from django.urls import path
from home.views import HomeView

app_name = "home"

urlpatterns = [
    path("",HomeView.as_view(), name="home"),
]

inventario/urls.py
from django.urls import path
from inventario.views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDelete, SubCategoriaView, SubCategoriaAdd, SubCategoriaEdit, SubCategoriaDelete, MarcaView, MarcaAdd, MarcaEdit, marca_disable, marca_enable, UniMedidasView, UniMedidasAdd, UniMedidasEdit,unimedida_disable, unimedida_enable, ProductoView, ProductoAdd, ProductoEdit, producto_enable, producto_disable

app_name = "inventario"

urlpatterns = [
    path("categorias/", CategoriaView.as_view(), name="categorias"),
    path("categorias/new", CategoriaNew.as_view(),name="categoria-new"),
    path("categoria/edit/<int:pk>", CategoriaEdit.as_view(), name="categoria-edit"),
    path("categoria/delete/<int:pk>", CategoriaDelete.as_view(), name="categoria-delete"),
    
    path("subcategorias/", SubCategoriaView.as_view(), name="subcategorias"),
    path("subcategorias/new",SubCategoriaAdd.as_view(), name="subcategoria-new"),
    path("subcategorias/edit/<int:pk>", SubCategoriaEdit.as_view(), name="subcategoria-edit"),
    path("subcategorias/delete/<int:pk>",SubCategoriaDelete.as_view(), name="subcategoria-delete"),
    
    path("marcas/", MarcaView.as_view(), name= "marcas"),
    path("marcas/new",MarcaAdd.as_view(),name="marca-new"),
    path("marcas/edit/<int:pk>", MarcaEdit.as_view(), name="marca-edit"),
    path("marcas/disable/<int:marca_id>", marca_disable , name="marca-disable"),
    path("marcas/enable/<int:marca_id>", marca_enable, name="marca-enable"),
    
    path("unimedidas/", UniMedidasView.as_view(), name="unimedidas"),
    path("unimedidas/new", UniMedidasAdd.as_view(), name="unimedida-new"),
    path("unimedidas/edit/<int:pk>", UniMedidasEdit.as_view(), name="unimedida-edit"),
    path("unimedidas/disable/<int:unimedida_id>",unimedida_disable, name="unimedida-disable"),
    path("unimedidas/enable/<int:unimedida_id>",unimedida_enable, name="unimedida-enable"),
    
    path("productos/", ProductoView.as_view(), name="productos"),
    path("productos/new",ProductoAdd.as_view(), name="producto-new" ),
    path("productos/edit/<int:pk>", ProductoEdit.as_view(), name="producto-edit"),
    path("productos/disable/<int:producto_id>", producto_disable, name="producto-disable"),
    path("productos/enable/<int:producto_id>", producto_enable, name="producto-enable"),
    
    
]

templates/components/logoutmodal.html
<div
  class="modal fade"
  id="logoutModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          ¿Cerrar Sesión para <mark>{{ user.username }}</mark>?
        </h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Al dar click en el botón Salir, cerrará la sesión para
        <mark>{{ user.username }}</mark>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Cancelar
        </button>
        <form method="POST" action="{% url 'logout' %}">
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">Salir</button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/components/sidebar.html
<ul
  class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
  id="accordionSidebar"
>
  <!-- Sidebar - Brand -->
  <a
    class="sidebar-brand d-flex align-items-center justify-content-center"
    href="{% url 'home:home' %}"
  >
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0" />

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'inventario:categorias' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a
    >
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider" />

  <!-- Heading -->
  <div class="sidebar-heading">Opciones del Menu</div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a
      class="nav-link collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#collapseTwo"
      aria-expanded="true"
      aria-controls="collapseTwo"
    >
      <i class="fas fa-fw fa-cog"></i>
      <span>Catalogos</span>
    </a>
    <div
      id="collapseTwo"
      class="collapse"
      aria-labelledby="headingTwo"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Catalogos del inventario</h6>
        <a class="collapse-item {% if '/categorias/' in request.path %}active{% endif %}" href="{% url 'inventario:categorias' %}">Categorias</a>
        <a class="collapse-item" href="{% url 'inventario:subcategorias' %}">Sub Categorias</a>
        <a class="collapse-item" href="{% url 'inventario:marcas' %}">Marcas</a>
        <a class="collapse-item" href=" {% url 'inventario:unimedidas' %}">Unidades de medida</a>

        <a class="collapse-item" href=" {% url 'inventario:productos' %}">Productos</a>

      </div>
    </div>
  </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a
      class="nav-link collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#collapseUtilities"
      aria-expanded="true"
      aria-controls="collapseUtilities"
    >
      <i class="fas fa-fw fa-wrench"></i>
      <span>Utilidades</span>
    </a>
    <div
      id="collapseUtilities"
      class="collapse"
      aria-labelledby="headingUtilities"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Items de los productos:</h6>
        <a class="collapse-item" href="utilities-animation.html">Animations</a>
        <a class="collapse-item" href="utilities-other.html">Other</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider" />

  <!-- Heading -->
  <div class="sidebar-heading">Addons</div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a
      class="nav-link collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#collapsePages"
      aria-expanded="true"
      aria-controls="collapsePages"
    >
      <i class="fas fa-fw fa-folder"></i>
      <span>Pages</span>
    </a>
    <div
      id="collapsePages"
      class="collapse"
      aria-labelledby="headingPages"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Login Screens:</h6>
        <a class="collapse-item" href="login.html">Login</a>
        <a class="collapse-item" href="register.html">Register</a>
        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
        <div class="collapse-divider"></div>
        <h6 class="collapse-header">Other Pages:</h6>
        <a class="collapse-item" href="404.html">404 Page</a>
        <a class="collapse-item" href="blank.html">Blank Page</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="charts.html">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Charts</span></a
    >
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="tables.html">
      <i class="fas fa-fw fa-table"></i>
      <span>Tables</span></a
    >
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block" />

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>

templates/components/topbar.html
{% load static %}

<nav
  class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
>
  <!-- Sidebar Toggle (Topbar) -->
  <button
    id="sidebarToggleTop"
    class="btn btn-link d-md-none rounded-circle mr-3"
  >
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <form
    class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
  >
    {% csrf_token %}
    <div class="input-group">
      <input
        type="text"
        class="form-control bg-light border-0 small"
        placeholder="Search for..."
        aria-label="Search"
        aria-describedby="basic-addon2"
      />
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="searchDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div
        class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
        aria-labelledby="searchDropdown"
      >
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input
              type="text"
              class="form-control bg-light border-0 small"
              placeholder="Search for..."
              aria-label="Search"
              aria-describedby="basic-addon2"
            />
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="alertsDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div
        class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="alertsDropdown"
      >
        <h6 class="dropdown-header">Alerts Center</h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold"
              >A new monthly report is ready to download!</span
            >
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your
            account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#"
          >Show All Alerts</a
        >
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="messagesDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div
        class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="messagesDropdown"
      >
        <h6 class="dropdown-header">Centro de Mensajes</h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img
              class="rounded-circle"
              src="https://source.unsplash.com/fn_BT9fwg_E/60x60"
              alt=""
            />
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">
              Hi there! I am wondering if you can help me with a problem I've
              been having.
            </div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img
              class="rounded-circle"
              src="https://source.unsplash.com/AU4VPcFN4LE/60x60"
              alt=""
            />
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">
              I have the photos that you ordered last month, how would you like
              them sent to you?
            </div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img
              class="rounded-circle"
              src="https://source.unsplash.com/CS2uCrpNzJY/60x60"
              alt=""
            />
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">
              Last month's report looks great, I am very happy with the progress
              so far, keep up the good work!
            </div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img
              class="rounded-circle"
              src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
              alt=""
            />
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">
              Am I a good boy? The reason I ask is because someone told me that
              people say this to all dogs, even if they aren't good...
            </div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#"
          >Read More Messages</a
        >
      </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="userDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"
          >{{user.username}}</span
        >
        <img
          class="img-profile rounded-circle"
          src=" {% static 'inventario/img/perfil.jpg' %} "
        />
      </a>
      <!-- Dropdown - User Information -->
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="userDropdown"
      >
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Perfil
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Configuracion
        </a>
        <div class="dropdown-divider"></div>
        <a
          class="dropdown-item"
          href="#"
          data-toggle="modal"
          data-target="#logoutModal"
        >
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Salir
        </a>
      </div>
    </li>
  </ul>
</nav>